### PR TITLE
Added basic code to calculate the magnitude function

### PR DESCRIPTION
**Pull request by lizliz**
Ok, first pass on adding in the code I had. I'm sure I'm forgetting something additional to do, particularly with documentation...... I tried to make sure the function has lots of description. Where else do I want to put this? More documentation somewhere?

### CODE REVIEW

**Comment by Pseudomanifold** [comment]
Sorry, don't know how to properly add to this request...but here's some code that calculates magnitude using a Cholesky decomposition.

```python

from scipy.linalg import cho_factor
from scipy.linalg import solve_triangular

[...]

M = np.exp(-D)
c, lower = cho_factor(M)
x = solve_triangular(c, np.ones(M.shape[0]), trans=1)

return x.T @ x
```

The idea is that the similarity matrix $\zeta$ is positive definite (under nice conditions), so it affords a Cholesky decomposition, which factorises as $L L^T$ for $L$ a lower-triangular matrix. Magnitude can be written as $\textrm{Mag}(X) = \mathbb{1}^T \zeta^{-1} \mathbb{1}$, i.e. a quadratic form (since we are taking row sums). Thus, calculating magnitude is equivalent to calculating $x^T x$ with $x$ defined by $Lx = \mathbb{1}$.

(We have described this a little bit in Appendix B of [a recent preprint](https://arxiv.org/abs/2311.16054))

Hope that helps!

**Comment by barnesd8** [comment]
@Pseudomanifold does that code need to be included in this merge as an additional function?

@lizliz do you want this approved without a unit test? We would also want to increment the version in the pyproject.toml so it can auto deploy to pypi.

**Comment by lizliz** [comment]
Don't approve yet, I should probably put this back to a draft while I finish doing the rest of the cleanup

**Comment by barnesd8** [comment]
@lizliz this also has to go into the test branch before master too

**Comment by Pseudomanifold** [comment]
@barnesd8 I think it could be included as an alternative calculation function

**Comment by barnesd8** [comment]
included in other pull request

**Pull request closed without merging**
